### ISSUE TITLE
Problem with Bucket Iterator Seemingly

### ISSUE THREAD

**Issue by aflah02** [pytorch/text#1448]
I've been trying to follow a youtube tutorial on Seq 2 Seq Attention Model Implementation

After coding and making modifications since the tutorial was old I am still facing this error which I think is due to the BucketIterator and I have no clue how to fix this. I tried playing with the repeat parameter but that didn't help out

My entire code is here - https://github.com/aflah02/Seq-2-Seq-Transformers-for-Machine-Translation

The error I get is this - 

`[Epoch 0 / 5]
=> Saving checkpoint
Translated example sentence: 
 ['<eos>']
Traceback (most recent call last):
  File "main.py", line 178, in <module>
    for batch_idx, batch in enumerate(train_iterator):
  File "/home/aflah/anaconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/legacy/data/iterator.py", line 145, in __iter__
    self.init_epoch()
  File "/home/aflah/anaconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/legacy/data/iterator.py", line 121, in init_epoch
    self.create_batches()
  File "/home/aflah/anaconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/legacy/data/iterator.py", line 252, in create_batches
    self.batches = pool(self.data(), self.batch_size,
  File "/home/aflah/anaconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/legacy/data/iterator.py", line 108, in data
    xs = [self.dataset[i] for i in self.random_shuffler(range(len(self.dataset)))]
  File "/home/aflah/anaconda3/envs/pytorch/lib/python3.7/site-packages/torchtext/legacy/data/iterator.py", line 108, in <listcomp>
    xs = [self.dataset[i] for i in self.random_shuffler(range(len(self.dataset)))]
  File "/home/aflah/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 69, in __getitem__
    raise NotImplementedError
NotImplementedError`

**Comment by parmeet** [comment]
Hi @aflah02, legacy BucketIterator is not compatible with torchtext's current datasets. We have deprecated legacy datasets in 0.9 release, please refer to corresponding [release notes](https://github.com/pytorch/text/releases/tag/v0.9.0-rc5). We also provide migration guide in this [tutorial](https://github.com/pytorch/text/blob/release/0.9/examples/legacy_tutorial/migration_tutorial.ipynb), you may refer to Step 3, to see how you can implement equivalent functionality as BucketIterator with current datasets.

**Comment by aflah02** [comment]
@parmeet Thanks a lot!
