### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '.data/snli/snli_1.0/snli_1.0_train.jsonl'

### ISSUE THREAD

**Issue by aotemandess** [pytorch/text#158]
when I run the newest code, it is like this:
**root@qzw:/home/qzw123/wangyuan/cove-fin# cd test
root@qzw:/home/qzw123/wangyuan/cove-fin/test# python example.py
Generating train, dev, test splits
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    train, dev, test = datasets.SNLI.splits(inputs, answers)
  File "/root/anaconda2/lib/python2.7/site-packages/torchtext/datasets/snli.py", line 68, in splits
    filter_pred=lambda ex: ex.label != '-')
  File "/root/anaconda2/lib/python2.7/site-packages/torchtext/data/dataset.py", line 63, in splits
    train_data = None if train is None else cls(path + train, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/torchtext/data/dataset.py", line 147, in __init__
    with io.open(os.path.expanduser(path), encoding="utf8") as f:
IOError: [Errno 2] No such file or directory: '.data/snli/snli_1.0/snli_1.0_train.jsonl'**

**Comment by jekbradbury** [comment]
Looks like the SNLI dataset was partially downloaded or downloaded in the wrong place? We don't do as much sanity checking there as we could; the easiest solution for now is probably just to `rm -r .data/snli/` and try again.
