### ISSUE TITLE
Dataset wouldn't be created.

### ISSUE THREAD

**Issue by ysangj** [pytorch/text#163]
I'm using pytorch without cuda in MAC OS in python 3.6. 
If I change the position of FR and EN, the code works fine.

```python
from torchtext import data
from torchtext import datasets

import re

FR = data.Field()
EN = data.Field()

train, val, test = datasets.IWSLT.splits(exts=('.en', '.fr'), fields=(EN, FR))
```

```
Traceback (most recent call last):
  File "torchtext_data_load.py", line 9, in <module>
    train, val, test = datasets.IWSLT.splits(exts=('.en', '.fr'), fields=(EN, FR))
  File "/Users/sangjunyum/anaconda/lib/python3.6/site-packages/torchtext-0.2.0-py3.6.egg/torchtext/datasets/translation.py", line 102, in splits
  File "/Users/sangjunyum/anaconda/lib/python3.6/site-packages/torchtext-0.2.0-py3.6.egg/torchtext/data/dataset.py", line 129, in download
  File "/Users/sangjunyum/anaconda/lib/python3.6/tarfile.py", line 1754, in getmembers
    self._load()        # all members, we first have to
  File "/Users/sangjunyum/anaconda/lib/python3.6/tarfile.py", line 2348, in _load
    tarinfo = self.next()
  File "/Users/sangjunyum/anaconda/lib/python3.6/tarfile.py", line 2279, in next
    self.fileobj.seek(self.offset - 1)
  File "/Users/sangjunyum/anaconda/lib/python3.6/gzip.py", line 368, in seek
    return self._buffer.seek(offset, whence)
  File "/Users/sangjunyum/anaconda/lib/python3.6/_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "/Users/sangjunyum/anaconda/lib/python3.6/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
172-17-86-250:project sangjunyum$ python torchtext_data_load.py
Traceback (most recent call last):
  File "torchtext_data_load.py", line 9, in <module>
    train, val, test = datasets.IWSLT.splits(exts=('.en', '.fr'), fields=(EN, FR))
  File "/Users/sangjunyum/anaconda/lib/python3.6/site-packages/torchtext-0.2.0-py3.6.egg/torchtext/datasets/translation.py", line 102, in splits
  File "/Users/sangjunyum/anaconda/lib/python3.6/site-packages/torchtext-0.2.0-py3.6.egg/torchtext/data/dataset.py", line 129, in download
  File "/Users/sangjunyum/anaconda/lib/python3.6/tarfile.py", line 1754, in getmembers
    self._load()        # all members, we first have to
  File "/Users/sangjunyum/anaconda/lib/python3.6/tarfile.py", line 2348, in _load
    tarinfo = self.next()
  File "/Users/sangjunyum/anaconda/lib/python3.6/tarfile.py", line 2279, in next
    self.fileobj.seek(self.offset - 1)
  File "/Users/sangjunyum/anaconda/lib/python3.6/gzip.py", line 368, in seek
    return self._buffer.seek(offset, whence)
  File "/Users/sangjunyum/anaconda/lib/python3.6/_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "/Users/sangjunyum/anaconda/lib/python3.6/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by nelson-liu** [comment]
This is probably due to an incomplete or corrputed download. Try to remove the downloaded file?
 I think it should be in `.data`, maybe where you ran it or wherever the torchtext install is?

 @jekbradbury It would probably be a good idea to compare downloads against a md5 hash before to verify that they were actually downloaded properly.

**Comment by jekbradbury** [comment]
Closing in favor of #158
