### ISSUE TITLE
Failed to import my built torchtext 

### ISSUE THREAD

**Issue by jiapei100** [pytorch/text#1928]
## ❓ Questions and Help

**Description**

```console
➜  ~ python
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torchtext as tt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.10/site-packages/torchtext/__init__.py", line 6, in <module>
    from torchtext import _extension  # noqa: F401
  File "~/.local/lib/python3.10/site-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "~/.local/lib/python3.10/site-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "~/.local/lib/python3.10/site-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "~/.local/lib/python3.10/site-packages/torch/_ops.py", line 568, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ~/.local/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZTVN5torch8autograd12AutogradMetaE
>>> 

```

My **torch** and **torchtext** are respectively installed as:

```console
➜  ~ pip show torch
Name: torch
Version: 1.13.0a0+git71dddec
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: ~/.local/lib/python3.10/site-packages
Requires: typing-extensions
Required-by: functorch, lpips, thop, timm, torchdata, torchtext, torchvision
➜  ~ pip show torchtext
Name: torchtext
Version: 0.14.0a0+3f9c349
Summary: Text utilities and datasets for PyTorch
Home-page: https://github.com/pytorch/text
Author: PyTorch core devs and James Bradbury
Author-email: jekbradbury@gmail.com
License: BSD
Location: ~/.local/lib/python3.10/site-packages
Requires: numpy, requests, torch, tqdm
Required-by: 
```

Any suggestions please??

**Comment by cherry-licongyi** [comment]
the same situation encountered after I installed torchdata on colab

**Comment by Nayef211** [comment]
@cherry-licongyi sorry for the late response here. Is this still happening? Could you link a minimal repro on a colab notebook?

**Comment by cherry-licongyi** [comment]
> @cherry-licongyi sorry for the late response here. Is this still happening? Could you link a minimal repro on a colab notebook?

https://colab.research.google.com/drive/1rk223wM0AwLkWHbmpzDPgr0iyf-a4B2Y?usp=sharing

**Comment by jemisjoky** [comment]
I'm getting the same error when I try importing torchtext. Running `echo "import torch, torchtext" > debug.txt; python debug.txt` in the terminal gives this error:

```
Traceback (most recent call last):
  File "debug.txt", line 1, in <module>
    import torch, torchtext
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/torchtext/__init__.py", line 6, in <module>
    from torchtext import _extension  # noqa: F401
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/torchtext/lib/libtorchtext.so, 0x0006): Symbol not found: __ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEENS6_INS2_12MemoryFormatEEE
  Referenced from: <A44C61F6-6A84-3C16-9DE4-6EEA370B5D71> /Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/torchtext/lib/libtorchtext.so
  Expected in:     <58CCB522-22AD-3792-941D-5888ED03E35C> /Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages/torch/lib/libtorch_cpu.dylib
```

My torch and torchtext were both installed through pip, and here is the info for the installations:

```
Name: torch
Version: 1.12.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages
Requires: typing-extensions
Required-by: torchdata, torchtext, torchvision
```

```
Name: torchtext
Version: 0.14.0
Summary: Text utilities and datasets for PyTorch
Home-page: https://github.com/pytorch/text
Author: PyTorch core devs and James Bradbury
Author-email: jekbradbury@gmail.com
License: BSD
Location: /Users/jemis/opt/miniconda3/envs/umps38/lib/python3.8/site-packages
Requires: numpy, requests, torch, tqdm
Required-by:
```

Oh, and I'm running this on an M1 Mac, don't know if that could be part of the issue...

**Comment by jemisjoky** [comment]
Disregard that last comment, just found [this issue](https://github.com/pytorch/text/issues/1988) and downgrading to torchtext 0.13.0 fixed the issue!

**Comment by Nayef211** [comment]
Awesome glad you were able to figure this out!

**Comment by jemisjoky** [comment]
Thanks @Nayef211! I don't think my issue was ultimately the same as that of the OP though, since they appear to have compatible Torchtext and Pytorch versions. Not sure if this issue is really closed. Any thoughts @jiapei100 @cherry-licongyi?

**Comment by Nayef211** [comment]
> Thanks @Nayef211! I don't think my issue was ultimately the same as that of the OP though, since they appear to have compatible Torchtext and Pytorch versions. Not sure if this issue is really closed. Any thoughts @jiapei100 @cherry-licongyi?

Oh my mistake, @jiapei100 feel free to reopen this issue if you're still running into the same problem.

**Comment by Luismbpr** [comment]
Had a similar issue and downgraded to this specific version
´´´shell
pip uninstall torch
pip install torch==2.3.0
pip install torchtext==0.18
```
Source: https://discuss.pytorch.org/t/unable-to-import-torchtext-from-torchtext-datasets-import-imdb-from-torchtext-vocab-import-vocab/207843

**Comment by pradyuprasad** [comment]
Can confirm that @Luismbpr solution worked!
