### ISSUE TITLE
Can't import torchtext

### ISSUE THREAD

**Issue by xwang233** [pytorch/text#1965]
## 🐛 Bug

**Describe the bug** A clear and concise description of what the bug is.

Can't import torchtext

**To Reproduce** Steps to reproduce the behavior:

```python
$ python -c 'import torch; import torchtext'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/pytorch/text/torchtext/__init__.py", line 12, in <module>
    from . import data, datasets, prototype, functional, models, nn, transforms, utils, vocab, experimental
  File "/opt/pytorch/text/torchtext/datasets/__init__.py", line 3, in <module>
    from .ag_news import AG_NEWS
  File "/opt/pytorch/text/torchtext/datasets/ag_news.py", line 5, in <module>
    from torchdata.datapipes.iter import FileOpener, IterableWrapper
  File "/opt/conda/lib/python3.8/site-packages/torchdata-0.4.1-py3.8-linux-x86_64.egg/torchdata/__init__.py", line 9, in <module>
    from . import datapipes
  File "/opt/conda/lib/python3.8/site-packages/torchdata-0.4.1-py3.8-linux-x86_64.egg/torchdata/datapipes/__init__.py", line 9, in <module>
    from . import iter, map, utils
  File "/opt/conda/lib/python3.8/site-packages/torchdata-0.4.1-py3.8-linux-x86_64.egg/torchdata/datapipes/iter/__init__.py", line 64, in <module>
    from torchdata.datapipes.iter.transform.callable import (
  File "/opt/conda/lib/python3.8/site-packages/torchdata-0.4.1-py3.8-linux-x86_64.egg/torchdata/datapipes/iter/transform/callable.py", line 10, in <module>
    from torch.utils.data.datapipes.utils.common import _check_lambda_fn
ImportError: cannot import name '_check_lambda_fn' from 'torch.utils.data.datapipes.utils.common' (/opt/pytorch/pytorch/torch/utils/data/datapipes/utils/common.py)
```

**Expected behavior** A clear and concise description of what you expected to happen.

import should work

**Screenshots** If applicable, add screenshots to help explain your problem.

N/A

**Environment**

torch_commit: https://github.com/pytorch/pytorch/commit/701b3dd77380bb0f7e696c9511b8ee765488687d
torchtext_commit: https://github.com/pytorch/text/commit/0208a0ed4fa5f55e1e50cc26c24cb7a132e0d62f

**Additional context** Add any other context about the problem here.

However, using this torchtext commit works 5c402176d8456d572cad3ccd295fcfed2021e8d4. I guess https://github.com/pytorch/text/pull/1961 is related.

cc @abhinavarora @ejguan @ngimel

**Comment by ejguan** [comment]
It's apparently the wrong version of torchdata is installed here.
Do you mind reinstall `torchdata` via nightly release?

**Comment by xwang233** [comment]
We don't have torchdata explicitly installed in our environment. We build pytorch and torchtext from the latest github source with `python setup.py develop`. Do you know if a wrong version of torchdata is installed along with pytorch or torchtext?

**Comment by ejguan** [comment]
Understood, torchtext now adds a hard dependency on torchdata. So if you install everything from scratch, you have to install torchdata from scratch as well.
And, for TorchText side, on the main branch, a specific version of torchdata should be specified like `torchdata>0.5` in `setup.py` to make sure a proper dependency error is raised during installation.

**Comment by ejguan** [comment]
cc: @Nayef211 @abhinavarora

**Comment by xwang233** [comment]
> So if you install everything from scratch, you have to install torchdata from scratch as well.

Thanks for the clarifications. We'll try to install the torchdata nightly wheel. Please feel free to close this issue if it's resolved on your side as well.

**Comment by joecummings** [comment]
Closing this as resolved.
