### ISSUE TITLE
Torchtext addresses empty memory and fails with OSError

### ISSUE THREAD

**Issue by realprogrammersusevim** [pytorch/text#1988]
### Description

Torchtext installed correctly with pip but whenever I try to import the module it fails immediately. Here's the full traceback:

```yaml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/torchtext/__init__.py", line 6, in <module>
    from torchtext import _extension  # noqa: F401
  File "/opt/homebrew/lib/python3.10/site-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/opt/homebrew/lib/python3.10/site-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/opt/homebrew/lib/python3.10/site-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/opt/homebrew/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so, 0x0006): Symbol not found: __ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIxEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  Referenced from: <B003263D-0AE9-3617-8F11-B4B7AF03C09F> /opt/homebrew/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so
  Expected in:     <0BB917BA-0D8F-3429-B798-476DA4A619BD> /opt/homebrew/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
```

If this is a bug then my apologies, I just had a feeling that I was doing something wrong.

### Environment

If it helps you at all here's the relevant information. One issue I had thought of was that I installed the torch and torchdata developer versions. I believe I did so to make sure they supported the arm64 architecture (M1).

```
Operating System: macOS 13.0
Architecture: arm64
Python: 3.10.8
Torchtext: 0.13.1
Torchdata: 0.6.0.dev20221116
Torch: 1.14.0.dev20221116
```

**Comment by mthrok** [comment]
You have unmatching versions of PyTorch and torchtext. Your torchtext is older than the others.

**Comment by realprogrammersusevim** [comment]
Thank you so much. I had installed the dev versions of torch  to try and take advantage of some new GPU acceleration for Apple Silicon. I installed the correct stable versions of everything and it's all working great now.
