### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by fizwit** [pytorch/text#2270]
## undefined symbol

PyTorch version 2.1.2

I am looking for a version of torchtext that will work with PyTorch 2.1.2.  I have tried every version from 0.16.0 to 0.18.0
Each version of torchtext has some version of undefined symbol. 

```
python -c "import torchtext"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/software/scGPT/0.2.1-foss-2023a/lib/python3.11/site-packages/torchtext/__init__.py", line 6, in <module>
    from torchtext import _extension  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/software/scGPT/0.2.1-foss-2023a/lib/python3.11/site-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/app/software/scGPT/0.2.1-foss-2023a/lib/python3.11/site-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/app/software/scGPT/0.2.1-foss-2023a/lib/python3.11/site-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/app/software/PyTorch/2.1.2-foss-2023a/lib/python3.11/site-packages/torch/_ops.py", line 852, in load_library
    ctypes.CDLL(path)
  File "/app/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /app/software/scGPT/0.2.1-foss-2023a/lib/python3.11/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN5torch6detail10class_baseC2ERKSsS3_SsRKSt9type_infoS6_
```

**Comment by peach-water** [comment]
I have the same questions, Anyone can helps?
