### ISSUE TITLE
RuntimeError: torch.LongTensor constructor doesn't accept any keyword arguments

### ISSUE THREAD

**Issue by tuvuumass** [pytorch/text#305]
I got this error when running text/test/snli.py.

```
Traceback (most recent call last):
  File "text/test/snli.py", line 19, in <module>
    batch = next(iter(train_iter))
  File "torchtext/data/iterator.py", line 157, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "torchtext/data/batch.py", line 27, in __init__
    setattr(self, name, field.process(batch, device=device))
  File "torchtext/data/field.py", line 188, in process
    tensor = self.numericalize(padded, device=device)
  File "torchtext/data/field.py", line 310, in numericalize
    var = self.tensor_type(arr, device=device)
RuntimeError: torch.LongTensor constructor doesn't accept any keyword arguments
```

**Comment by mttk** [comment]
should be fixed by #302
