### ISSUE TITLE
Loading WMT14 dataset failed.

### ISSUE THREAD

**Issue by cswhjiang** [pytorch/text#325]
The code to load WMT14 dataset:
```
from torchtext import data
from torchtext import datasets

import re
import spacy

spacy_de = spacy.load('de')
spacy_en = spacy.load('en')

def tokenize_de(text):
    return [tok.text for tok in spacy_de.tokenizer(text)]

def tokenize_en(text):
    return [tok.text for tok in spacy_en.tokenizer(text)]


BOS_WORD = '<s>'
EOS_WORD = '</s>'
BLANK_WORD = "<blank>"
SRC = data.Field(tokenize=tokenize_de, pad_token=BLANK_WORD)
TGT = data.Field(tokenize=tokenize_en, init_token=BOS_WORD, eos_token=EOS_WORD, pad_token=BLANK_WORD)

MAX_LEN = 100
print('splits')
train, val, test = datasets.WMT14.splits(
    exts=('.de', '.en'), fields=(SRC, TGT),
    filter_pred=lambda x: len(vars(x)['src']) <= MAX_LEN and len(vars(x)['trg']) <= MAX_LEN)

print(train.fields)
print(len(train))
print(vars(train[0]))
print(vars(train[100]))
```

Error message:
```
splits
Traceback (most recent call last):
  File "test_wmt14.py", line 27, in <module>
    filter_pred=lambda x: len(vars(x)['src']) <= MAX_LEN and len(vars(x)['trg']) <= MAX_LEN)
  File "/usr/local/lib/python3.6/site-packages/torchtext/datasets/translation.py", line 209, in splits
    exts, fields, root, train, validation, test, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torchtext/datasets/translation.py", line 64, in splits
    os.path.join(path, train), exts, fields, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torchtext/datasets/translation.py", line 33, in __init__
    with open(src_path) as src_file, open(trg_path) as trg_file:
FileNotFoundError: [Errno 2] No such file or directory: '.data/newstest2013.tok.bpe.32000.de'
```

**Comment by domaala** [comment]
Probably the same as #312.

**Comment by zhangguanheng66** [comment]
@cswhjiang if you still have such an issue, feel free to reopen it.
