### ISSUE TITLE
Bug in Last Commit: Missing function len() in type Example

### ISSUE THREAD

**Issue by phohenecker** [pytorch/text#39]
Hi everyone!

It seems like the last commit of `data.py` by @jekbradbury introduced a bug. Here's the stacktrace of my code that works with the second last revision (https://github.com/pytorch/text/commit/8b5c731794199188879d0e8d2a8db179e6780bf3)
```
Traceback (most recent call last):
  File "/data/mulga/oana-2/anaconda3/envs/nips-2017/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/mulga/oana-2/anaconda3/envs/nips-2017/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/mulga/oana-2/experiments/src/main/python/nips2017/__main__.py", line 207, in main
    exp.run()
  File "/data/mulga/oana-2/experiments/src/main/python/nips2017/experiment/base_experiment.py", line 431, in run
    self._train(epoch)
  File "/data/mulga/oana-2/experiments/src/main/python/nips2017/experiment/experiment_2.py", line 375, in _train
    for iteration, batch in enumerate(self._data.training_iter, 1):
  File "/data/mulga/oana-2/anaconda3/envs/nips-2017/lib/python3.6/site-packages/torchtext/data.py", line 589, in __iter__
    for minibatch in self.batches:
  File "/data/mulga/oana-2/anaconda3/envs/nips-2017/lib/python3.6/site-packages/torchtext/data.py", line 463, in pool
    for p in batch(data, batch_size * 100, batch_size_fn):
  File "/data/mulga/oana-2/anaconda3/envs/nips-2017/lib/python3.6/site-packages/torchtext/data.py", line 442, in batch
    size_so_far += batch_size_fn(ex)
TypeError: object of type 'Example' has no len()
```
I didn't have a detailed look at it yet, and can provide a minimal example that reproduces the bug later, but I suppose the stacktrace might already be enough for you guys to know what's going on.

Best,
Patrick

**Comment by jekbradbury** [comment]
Thanks for the report. Should be fixed in 6bad29a.

**Comment by JianLiu91** [comment]
Hi, this problem becomes     
```
batch = next(iter(train_iter))
  File "build/bdist.linux-x86_64/egg/torchtext/data.py", line 590, in __iter__
  File "build/bdist.linux-x86_64/egg/torchtext/data.py", line 463, in pool
  File "build/bdist.linux-x86_64/egg/torchtext/data.py", line 442, in batch
TypeError: <lambda>() takes no arguments (1 given)
```

**Comment by jekbradbury** [comment]
How about now?

**Comment by phohenecker** [comment]
Just checked out https://github.com/pytorch/text/commit/d3a20115396d118ea19121f44472935b0afe5d45, and it works.

**Comment by nelson-liu** [comment]
Perhaps this should be closed?
