### ISSUE TITLE
error when load vector

### ISSUE THREAD

**Issue by woyijkl1** [pytorch/text#507]
I successfully run the following code:
vec = vocab.Vectors('glove.twitter.27B.50d.txt',r'/home/yinrongdi/vector',unk_init=torch.nn.init.xavier_uniform)
but,to run this code:
txt_field.build_vocab(train_set , vectors=vec)
will cause (when torchtext version is 0.3.+ will cause but when torchtext version is 0.2.3 will not cause)
 ValueError: Fan in and fan out can not be computed for tensor with less than 2 dimensions

and the whole error is as follows:
Traceback (most recent call last):

File "/home/lxy/new20g_disk/3a_research/pytorch_Test/vectors.py", line 79, in 
TEXT.build_vocab(train, vectors=vectors)

File "/home/lxy/anaconda3/lib/python3.5/site-packages/torchtext/data/field.py", line 273, in build_vocab
self.vocab = self.vocab_cls(counter, specials=specials, **kwargs)

File "/home/lxy/anaconda3/lib/python3.5/site-packages/torchtext/vocab.py", line 88, in **init**
self.load_vectors(vectors, unk_init=unk_init, cache=vectors_cache)

File "/home/lxy/anaconda3/lib/python3.5/site-packages/torchtext/vocab.py", line 159, in load_vectors
self.vectors[i][start_dim:end_dim] = v[token.strip()]

File "/home/lxy/anaconda3/lib/python3.5/site-packages/torchtext/vocab.py", line 286, in **getitem**
return self.unk_init(torch.Tensor(self.dim))

File "/home/lxy/anaconda3/lib/python3.5/site-packages/torch/nn/init.py", line 218, in xavier_uniform_
fan_in, fan_out = _calculate_fan_in_and_fan_out(tensor)

File "/home/lxy/anaconda3/lib/python3.5/site-packages/torch/nn/init.py", line 181, in _calculate_fan_in_and_fan_out
raise ValueError("Fan in and fan out can not be computed for tensor with less than 2 dimensions")

ValueError: Fan in and fan out can not be computed for tensor with less than 2 dimensions

so, how can I fix it
thanks

**Comment by Nayef211** [comment]
Closing this as we no longer have `torchtext.vocab.Vectors` in our library. Feel free to try out `torchtext.prototype.vectors.Vectors` to verify if you're running into this issue!
