### ISSUE TITLE
Field information unavailable for validation set using BucketIterator.splits

### ISSUE THREAD

**Issue by ZeerakW** [pytorch/text#617]
When generating data splits using BucketIterator.splits the fields are only applicable on the train data, meaning that it's impossible to iterate through dev or test splits.

Following [example 5](https://pytorch.org/text/examples.html) in the docs the issue occurs when iterating over the dev or test splits.

Running the code below 

```python
from torchtext.data import BucketIterator, TabularDataset, Field

text = Field(sequential = True,
                  include_lengths=True,
                  use_vocab=True)
label = Field(sequential = False,
              include_lengths = False,
              use_vocab = True,
              pad_token = None,
              unk_token = None)

fields = [('id', None),
          ('bad_word', text),
          ('question', text),
          ('question_sentiment_gold', label),
          ('answer', text),
          ('answer_sentiment_gold', label),
          ('username', text)]

train, dev, test = TabularDataset.splits(path = '~/Documents/project/data/',
                                         format = 'csv',
                                         fields = fields,
                                         train = 'train.csv', validation = 'dev.csv', test = 'test.csv',
                                         skip_header = True)

train_iter, dev_iter, test_iter = BucketIterator.splits((train, dev, test),
                                                        batch_sizes = (32, 32, 32),
                                                        sort_key = lambda x: len(x.question),
                                                        device = 'cpu')

print(train, dev, test)

text.build_vocab(train)
label.build_vocab(train)

print("Train iter", next(iter(train_iter)))
print("Test iter", next(iter(test_iter)))
print("dev iter", next(iter(dev_iter)))
```
produces the correct output:

```python
<torchtext.data.dataset.TabularDataset object at 0x10f6974d0> <torchtext.data.dataset.TabularDataset object at 0x1182c8b50> <torchtext.data.dataset.TabularDataset object at 0x118290ad0>
Train iter
[torchtext.data.batch.Batch of size 32]
	[.bad_word]:('[torch.LongTensor of size 1x32]', '[torch.LongTensor of size 32]')
	[.question]:('[torch.LongTensor of size 57x32]', '[torch.LongTensor of size 32]')
	[.question_sentiment_gold]:[torch.LongTensor of size 32]
	[.answer]:('[torch.LongTensor of size 47x32]', '[torch.LongTensor of size 32]')
	[.answer_sentiment_gold]:[torch.LongTensor of size 32]
	[.username]:('[torch.LongTensor of size 1x32]', '[torch.LongTensor of size 32]')
Test iter
[torchtext.data.batch.Batch of size 32]
	[.bad_word]:('[torch.LongTensor of size 1x32]', '[torch.LongTensor of size 32]')
	[.question]:('[torch.LongTensor of size 4x32]', '[torch.LongTensor of size 32]')
	[.question_sentiment_gold]:[torch.LongTensor of size 32]
	[.answer]:('[torch.LongTensor of size 126x32]', '[torch.LongTensor of size 32]')
	[.answer_sentiment_gold]:[torch.LongTensor of size 32]
	[.username]:('[torch.LongTensor of size 1x32]', '[torch.LongTensor of size 32]')
```

and this traceback

```python
Traceback (most recent call last):
  File "tester.py", line 93, in <module>
    print("dev iter", next(iter(dev_iter)))
  File "/Users/zee/.virtualenvs/generalisable/lib/python3.7/site-packages/torchtext/data/iterator.py", line 141, in __iter__
    self.init_epoch()
  File "/Users/zee/.virtualenvs/generalisable/lib/python3.7/site-packages/torchtext/data/iterator.py", line 117, in init_epoch
    self.create_batches()
  File "/Users/zee/.virtualenvs/generalisable/lib/python3.7/site-packages/torchtext/data/iterator.py", line 245, in create_batches
    self.batches = batch(self.data(), self.batch_size,
  File "/Users/zee/.virtualenvs/generalisable/lib/python3.7/site-packages/torchtext/data/iterator.py", line 102, in data
    xs = sorted(self.dataset, key=self.sort_key)
  File "tester.py", line 83, in <lambda>
    sort_key = lambda x: len(x.question),
AttributeError: 'Example' object has no attribute 'question'
```

**Environment**

 - PyTorch Version (e.g., 1.0): 1.2.0
 - OS (e.g., Linux): OSX 10.14.5
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7.4

**Comment by zhangguanheng66** [comment]
@mttk any ideas?

**Comment by ZeerakW** [comment]
@mttk so that would be strange because the test and dev sets are the same and they're both just the last 500 rows + header of the train file. I've e-mailed you the file because I can't seem to find the URL again.

**Comment by ZeerakW** [comment]
I've looked more into this and it only happened with that one dataset and in the files generated by @mttk (and when I tried regenerating them myself) it didn't happen.
