### ISSUE TITLE
DLL load failure on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/text#868]
## 🐛 Bug
**Describe the bug**
```
(base) circleci@PACKER-5EFB90C1 C:\Users\circleci\project>pip install --pre torch torchvision torchaudio torchtext -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html 
Looking in links: https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/cu102/torch-1.7.0.dev20200702-cp37-cp37m-win_amd64.whl (1078.9 MB)
Collecting torchvision
  Downloading https://download.pytorch.org/whl/nightly/cu102/torchvision-0.8.0.dev20200701-cp37-cp37m-win_amd64.whl (1.1 MB)
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/nightly/torchaudio-0.7.0.dev20200701-cp37-none-win_amd64.whl (83 kB)
Collecting torchtext
  Downloading https://download.pytorch.org/whl/nightly/torchtext-0.8.0.dev20200701-cp37-cp37m-win_amd64.whl (1.4 MB)
Collecting numpy
  Downloading numpy-1.19.0-cp37-cp37m-win_amd64.whl (13.0 MB)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
Collecting pillow>=4.1.1
  Downloading Pillow-7.2.0-cp37-cp37m-win_amd64.whl (2.1 MB)
Collecting sentencepiece
  Downloading sentencepiece-0.1.91-cp37-cp37m-win_amd64.whl (1.2 MB)
Requirement already satisfied: tqdm in c:\users\circleci\project\conda\lib\site-packages (from torchtext) (4.46.0)
Requirement already satisfied: requests in c:\users\circleci\project\conda\lib\site-packages (from torchtext) (2.23.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\circleci\project\conda\lib\site-packages (from requests->torchtext) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\circleci\project\conda\lib\site-packages (from requests->torchtext) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\circleci\project\conda\lib\site-packages (from requests->torchtext) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\circleci\project\conda\lib\site-packages (from requests->torchtext) (2020.4.5.1)
Building wheels for collected packages: future
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491062 sha256=8fc90b1a20bac73666027a32891d6135a0eb367649a2d7bff47e0b1b5adbb888
  Stored in directory: c:\users\circleci\appdata\local\pip\cache\wheels\56\b0\fe\4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0
Successfully built future
ERROR: torchvision 0.8.0.dev20200701 has requirement torch==1.7.0.dev20200701, but you'll have torch 1.7.0.dev20200702 which is incompatible.
ERROR: torchaudio 0.7.0.dev20200701 has requirement torch==1.7.0.dev20200701+cu92, but you'll have torch 1.7.0.dev20200702 which is incompatible.
Installing collected packages: numpy, future, torch, pillow, torchvision, torchaudio, sentencepiece, torchtext
Successfully installed future-0.18.2 numpy-1.19.0 pillow-7.2.0 sentencepiece-0.1.91 torch-1.7.0.dev20200702 torchaudio-0.7.0.dev20200701 torchtext-0.8.0.dev20200701 torchvision-0.8.0.dev20200701

(base) circleci@PACKER-5EFB90C1 C:\Users\circleci\project\testcases>python -c "import torch" 

(base) circleci@PACKER-5EFB90C1 C:\Users\circleci\project\testcases>python -c "import torchtext" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\circleci\project\conda\lib\site-packages\torchtext\__init__.py", line 42, in <module>
    _init_extension()
  File "C:\Users\circleci\project\conda\lib\site-packages\torchtext\__init__.py", line 38, in _init_extension
    torch.ops.load_library(ext_specs.origin)
  File "C:\Users\circleci\project\conda\lib\site-packages\torch\_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "C:\Users\circleci\project\conda\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found
```

**To Reproduce**
1. pip install --pre torch torchtext -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html
2. python -c "import torchtext"

**Expected behavior**
Importing the library doesn't fail.

**Comment by peterjc123** [comment]
Upstream issue: https://github.com/pytorch/pytorch/issues/40998

**Comment by peterjc123** [comment]
Fixed by forcing triggering the update_s3_htmls job at PyTorch.
