### ISSUE TITLE
Where is version.py if I insist on building from source?

### ISSUE THREAD

**Issue by jiapei100** [pytorch/text#919]
When I tried to install by `pip setup.py build`, I obtained the following **ERROR** message:

```console
Traceback (most recent call last):
  File "setup.py", line 48, in <module>
    _export_version(VERSION, SHA)
  File "setup.py", line 42, in _export_version
    with open(version_path, 'w') as fileobj:
TypeError: expected str, bytes or os.PathLike object, not PosixPath
```

It looks **version.py** is missing.

Cheers

**Comment by mthrok** [comment]
This should be same as torchaudio. See https://github.com/pytorch/audio/issues/876#issuecomment-672796441

**Comment by zhangguanheng66** [comment]
@jiapei100 As @mthrok said, please follow our instruction to build from source code (a.k.a. `python setup.py clean install`)

**Comment by jiapei100** [comment]
@zhangguanheng66 

```console
:~/text$ python setup.py clean install
-- Building version 0.8.0a0+86f4465
running clean
Traceback (most recent call last):
  File "setup.py", line 114, in <module>
    setup(**setup_info)
  File "~/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 64, in run
    for path in (ROOT_DIR / 'torchtext').glob('**/*.so'):
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

Still failed to build after some tweaking.

**Comment by mthrok** [comment]
There is something wrong with your Python installation. `setuptools` is in your user package location, but it is referring to `distutils` in system location. Please use Anaconda Python for better environment management. Also please do not modify setup.py`, there is no way we can help you if you modify it.
