### ISSUE TITLE
experimental.AG_NEWS dataset fails to download, missing content-disposition

### ISSUE THREAD

**Issue by bertmaher** [pytorch/text#944]
## 🐛 Bug
**Describe the bug**
When downloading AG_NEWS, I get an error that the response does not contain content-disposition:
```
Traceback (most recent call last):
  File "agnews.py", line 3, in <module>
    train, test = AG_NEWS(ngrams=1)
  File "/Users/bertrand/src/text/torchtext/experimental/datasets/text_classification.py", line 147, in AG_NEWS
    return _setup_datasets(*(("AG_NEWS",) + args), **kwargs)
  File "/Users/bertrand/src/text/torchtext/experimental/datasets/text_classification.py", line 84, in _setup_datasets
    train, test = raw.DATASETS[dataset_name](root=root)
  File "/Users/bertrand/src/text/torchtext/experimental/datasets/raw/text_classification.py", line 96, in AG_NEWS
    return _setup_datasets(*(("AG_NEWS",) + args), **kwargs)
  File "/Users/bertrand/src/text/torchtext/experimental/datasets/raw/text_classification.py", line 67, in _setup_datasets
    dataset_tar = download_from_url(URLS[dataset_name], root=root)
  File "/Users/bertrand/src/text/torchtext/utils.py", line 132, in download_from_url
    return _process_response(response, root, filename)
  File "/Users/bertrand/src/text/torchtext/utils.py", line 67, in _process_response
    d = r.headers['content-disposition']
  File "/Users/bertrand/miniconda3/envs/hub/lib/python3.8/site-packages/requests-2.24.0-py3.8.egg/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
```

**To Reproduce**
```
from torchtext.experimental.datasets import AG_NEWS
train, test = AG_NEWS(ngrams=1)
```

**Expected behavior**
Downloaded dataset

**Environment**
```
Collecting environment information...
PyTorch version: 1.7.0.dev20200825
Is debug build: False
CUDA used to build PyTorch: 9.2

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Clang version: Could not collect
CMake version: version 3.7.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.2.88
GPU models and configuration: 
GPU 0: Tesla M40
GPU 1: Tesla M40

Nvidia driver version: 396.69
cuDNN version: /usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.1.2

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] numpy==1.19.1
[pip3] torch==1.7.0a0+a5bc709
[pip3] torch-struct==0.4
[pip3] torchfile==0.1.0
[pip3] torchtext==0.6.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               9.2                           0  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.1.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.1                   pypi_0    pypi
[conda] numpy-base                1.19.1           py37hfa32c7d_0  
[conda] pytorch                   1.7.0.dev20200825 py3.7_cuda9.2.148_cudnn7.6.3_0    pytorch-nightly
[conda] torch                     1.7.0a0+a5bc709          pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchtext                 0.8.0a0+8d0f7cb          pypi_0    pypi
```

**Comment by zhangguanheng66** [comment]
The site for downloading the raw data is now working properly now. A try later on may solve the problem.

**Comment by zhangguanheng66** [comment]
The link has recovered so I will close this issue. We are discussing an option to avoid this kind of issues although we don't want to host the data for legal reasons.
